#!/usr/bin/env bash
set -euo pipefail

git_bin="${GIT_BIN:-git}"; git_cmd() { "$git_bin" "$@"; }; fail_reason() { if [ -n "${UPSTREAM_SYNC_REPORT_PATH:-}" ]; then mkdir -p "$(dirname "$UPSTREAM_SYNC_REPORT_PATH")"; { echo '# Upstream synchronization failed'; echo; echo "- maintained SHA: \`$(git_cmd rev-parse HEAD 2>/dev/null || echo unknown)\`"; echo "- reason: \`$*\`"; } >"$UPSTREAM_SYNC_REPORT_PATH"; fi; echo "upstream_sync=failed reason=$*" >&2; exit 1; }
resolve_release() {
    : "${UPSTREAM_REPO:?UPSTREAM_REPO is required}"; : "${GITHUB_OUTPUT:?GITHUB_OUTPUT is required}"; error_file="$(mktemp)"
    if ! releases="$(gh api "repos/${UPSTREAM_REPO}/releases?per_page=100" 2>"$error_file")"; then cat "$error_file" >&2; fail_reason release_query_error repo="$UPSTREAM_REPO"; fi
    selected="$(jq -c '[.[] | select(.draft == false and .prerelease == false) | select(.tag_name != null and .tag_name != "")] | sort_by(.published_at) | last // empty' <<<"$releases")" || fail_reason release_response_malformed repo="$UPSTREAM_REPO"
    [ -n "$selected" ] && [ "$selected" != null ] || fail_reason no_stable_release repo="$UPSTREAM_REPO"
    tag="$(jq -r '.tag_name' <<<"$selected")"; version="${tag#v}"; url="$(jq -r '.html_url // .url // empty' <<<"$selected")"; published="$(jq -r '.published_at // empty' <<<"$selected")"; [ -n "$tag" ] || fail_reason latest_release_tag_missing repo="$UPSTREAM_REPO"
    if ! refs="$(git_cmd ls-remote "https://github.com/${UPSTREAM_REPO}.git" "refs/tags/${tag}" "refs/tags/${tag}^{}" 2>"$error_file")"; then cat "$error_file" >&2; fail_reason release_tag_query_error tag="$tag"; fi
    commit=""; while IFS=$'\t' read -r sha ref; do case "$ref" in "refs/tags/${tag}^{}") commit="$sha";; "refs/tags/${tag}") [ -n "$commit" ] || commit="$sha";; esac; done <<<"$refs"; [ -n "$commit" ] || fail_reason release_tag_commit_missing tag="$tag"
    { printf 'tag=%s\nversion=%s\nurl=%s\npublished_at=%s\ncommit=%s\n' "$tag" "$version" "$url" "$published" "$commit"; } >>"$GITHUB_OUTPUT"; echo "official_release repo=$UPSTREAM_REPO tag=$tag version=$version commit=$commit"
}
merge_upstream() {
    : "${UPSTREAM_REF:?UPSTREAM_REF is required}"; maintained_sha="$(git_cmd rev-parse HEAD)"; upstream_sha="$(git_cmd rev-parse --verify "$UPSTREAM_REF")" || fail_reason upstream_ref_missing ref="$UPSTREAM_REF"
    if git_cmd merge-base --is-ancestor "$upstream_sha" HEAD; then echo 'updated=false' >>"${GITHUB_OUTPUT:-/dev/null}"; echo 'workflow_changed=false' >>"${GITHUB_OUTPUT:-/dev/null}"; echo "upstream_sync=up_to_date maintained=$maintained_sha upstream=$upstream_sha"; return; fi
    merge_log="$(mktemp)"; if git_cmd merge --no-edit "$upstream_sha" >"$merge_log" 2>&1; then final_sha="$(git_cmd rev-parse HEAD)"; workflow_changed=false; if [ -n "$(git_cmd diff --name-only "$maintained_sha" "$final_sha" -- .github/workflows)" ]; then workflow_changed=true; fi; echo 'updated=true' >>"${GITHUB_OUTPUT:-/dev/null}"; echo "workflow_changed=$workflow_changed" >>"${GITHUB_OUTPUT:-/dev/null}"; echo "upstream_sync=merged maintained=$maintained_sha upstream=$upstream_sha final=$final_sha workflow_changed=$workflow_changed"; return; else merge_rc=$?; fi
    merge_output="$(cat "$merge_log")"; conflict_files="$(git_cmd diff --name-only --diff-filter=U || true)"; status_output="$(git_cmd status --short || true)"; report="${UPSTREAM_SYNC_REPORT_PATH:-upstream-sync-report.md}"; mkdir -p "$(dirname "$report")"; { echo '# Upstream synchronization stopped: merge conflict'; echo; echo "- maintained SHA: \`$maintained_sha\`"; echo "- upstream SHA: \`$upstream_sha\`"; echo '- status before abort:'; echo '```text'; printf '%s\n' "$status_output"; echo '```'; echo; echo '## Conflicting files'; if [ -n "$conflict_files" ]; then while IFS= read -r f; do printf '%s\n' "- \`$f\`"; done <<<"$conflict_files"; else echo '- none'; fi; echo; echo '## Merge output'; echo '```text'; printf '%s\n' "$merge_output"; echo '```'; } >"$report"
    if ! git_cmd merge --abort >/dev/null 2>&1; then echo "upstream_sync=failed reason=merge_abort_failed report=$report" >&2; exit 1; fi; echo "upstream_sync=conflict maintained=$maintained_sha upstream=$upstream_sha report=$report" >&2; exit "$merge_rc"
}
release_file_contract() { : "${UPSTREAM_REF:?UPSTREAM_REF is required}"; path="${RELEASE_FILE_PATH:-current-release.md}"; [ -f "$path" ] || fail_reason release_file_missing path="$path"; if ! expected="$(git_cmd show "$UPSTREAM_REF:$path")"; then fail_reason release_source_missing path="$path" upstream="$UPSTREAM_REF"; fi; actual="$(<"$path")"; [ "$expected" = "$actual" ] || { echo "release_file_mismatch path=$path upstream=$UPSTREAM_REF" >&2; exit 1; }; grep -Eq '^Backend: v[0-9]+\.[0-9]+\.[0-9]+$' "$path" || fail_reason release_file_malformed path="$path" field=Backend; grep -Eq '^Frontend: v[0-9]+\.[0-9]+\.[0-9]+$' "$path" || fail_reason release_file_malformed path="$path" field=Frontend; echo "release_contract=checked path=$path"; echo 'release_contract=passed'; }
package_contract() { : "${UPSTREAM_REF:?UPSTREAM_REF is required}"; IFS=',' read -r -a paths <<<"${PACKAGE_PATHS:-package.json}"; for path in "${paths[@]}"; do [ -f "$path" ] || fail_reason package_file_missing path="$path"; expected_json="$(git_cmd show "$UPSTREAM_REF:$path")" || fail_reason package_source_missing path="$path"; expected="$(jq -er '.version // empty' <<<"$expected_json")" || fail_reason package_version_missing path="$path"; actual="$(jq -er '.version // empty' "$path")" || fail_reason package_version_missing path="$path"; [ "$expected" = "$actual" ] || { echo "package_version_mismatch path=$path expected=$expected actual=$actual upstream=$UPSTREAM_REF" >&2; exit 1; }; echo "package_contract=checked path=$path version=$actual"; done; echo 'package_contract=passed'; }
capability_preflight() { : "${GITHUB_REPOSITORY:?GITHUB_REPOSITORY is required}"; if [ "${WORKFLOW_CHANGED:-false}" = true ] && [ -z "${WORKFLOW_TOKEN:-}" ]; then fail_reason missing_WORKFLOW_TOKEN workflow_files_changed; fi; error_file="$(mktemp)"; if ! repo_id="$(gh api "repos/${GITHUB_REPOSITORY}" --jq .id 2>"$error_file")" || [ -z "$repo_id" ]; then cat "$error_file" >&2; fail_reason repository_query_error; fi; gh api "repos/${GITHUB_REPOSITORY}/releases?per_page=1" >/dev/null 2>&1 || fail_reason release_query_error; log="$(mktemp)"; preflight_ref="refs/heads/singbox-capability-preflight-${GITHUB_RUN_ID:-local}"; if ! git_cmd push --dry-run origin "HEAD:$preflight_ref" >"$log" 2>&1; then cat "$log" >&2; fail_reason contents_write_dry_run_denied; fi; echo "capability_preflight=passed repository_id=$repo_id contents=write release=read workflow_changed=${WORKFLOW_CHANGED:-false}"; }
case "${1:-}" in resolve) resolve_release;; merge) merge_upstream;; release-file) release_file_contract;; package) package_contract;; preflight) capability_preflight;; *) echo 'usage: upstream-sync-lib.sh {resolve|merge|release-file|package|preflight}' >&2; exit 2;; esac
